version: '3'

services:
  client:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    networks:
      - network
    environment:
      - CONFIG=/config/config.yaml
    ports:
      - "8080:8080"

networks:
  network:
    driver: bridge