version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: auth_service/cmd/Dockerfile
    expose:
      - "32100"
    depends_on:
      - auth_db
    volumes:
      - auth_db-data:/auth_service/storage
    networks:
      - network
    environment:
      - CONFIG=/config/config.yaml
  auth_db:
    build:
      context: .
      dockerfile: auth_service/storage/Dockerfile
    volumes:
      - auth_db-data:/auth_service/storage
    networks:
      - network

  chat:
    build:
      context: .
      dockerfile: chat_service/cmd/Dockerfile
    volumes:
      - chat_db-data:/chat_service/storage
    expose:
      - "32200"
    depends_on:
      - auth
      - kafka
      - chat_db
    networks:
      - network
    environment:
      - CONFIG=/config/config.yaml
  chat_db:
    build:
      context: .
      dockerfile: chat_service/storage/Dockerfile
    volumes:
      - chat_db-data:/chat_service/storage
    networks:
      - network

  client:
    build:
      context: .
      dockerfile: client/cmd/Dockerfile
    environment:
      - CONFIG=/config/config.yaml
    volumes:
      - ./client/cmd/tmp:/client/cmd/tmp
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - chat
    networks:
      - network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    networks:
      - network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  auth_db-data:
  chat_db-data:

networks:
  network:
    driver: bridge