proto-auth:
	protoc -I auth_service/proto --go_out=auth_service/proto/gen --go_opt=paths=source_relative \
  	--go-grpc_out=auth_service/proto/gen --go-grpc_opt=paths=source_relative ./auth_service/proto/auth.proto
proto-chat:
	protoc -I chat_service/proto --go_out=chat_service/proto/gen --go_opt=paths=source_relative \
  	--go-grpc_out=chat_service/proto/gen --go-grpc_opt=paths=source_relative ./chat_service/proto/chat.proto