proto-auth:
	protoc -I protos/proto --go_out=protos/gen/auth --go_opt=paths=source_relative \
  	--go-grpc_out=protos/gen/auth --go-grpc_opt=paths=source_relative ./protos/proto/auth.proto
proto-chat:
	protoc -I protos/proto --go_out=protos/gen/chat --go_opt=paths=source_relative \
  	--go-grpc_out=protos/gen/chat --go-grpc_opt=paths=source_relative ./protos/proto/chat.proto


chat:
	go run app/cmd/services/chat/main.go --config=app/config/local.yaml
auth:
	go run app/cmd/services/auth/main.go --config=app/config/local.yaml
client:
	go run app/cmd/client/main.go --config=app/config/local.yaml

migrate:
	go run app/cmd/migrator/main.go --storage-path=app/storage/app.sqlite --migrations-path=app/migrations