version: '3'

services:
  chat:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    volumes:
      - db-data:/storage
    expose:
      - "32200"
    depends_on:
      - storage
    networks:
      - network
    environment:
      - CONFIG=/config/config.yaml

  storage:
    build:
      context: .
      dockerfile: ./storage/Dockerfile
    volumes:
      - db-data:/storage
    networks:
      - network

volumes:
  db-data:

networks:
  network:
    driver: bridge